services:
  app2:
    container_name: app-pos
    image: ghcr.io/andsr157/pos-app:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`pos.dancok.fun`)"
      - "traefik.http.routers.app2.entrypoints=websecure"
      - "traefik.http.routers.app2.tls.certresolver=myresolver"
    volumes: []
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always
    networks:
      - traefik_web

networks:
  traefik_web:
    external: true
